syntax = "proto3";
package com.abolfazlMokhtari.pounes.proto;

message Users {
   repeated User users = 1;
}

message User {
  int64 telegramId = 1;
  repeated Liker likers = 2;
}

message Liker {
  string _id = 1;
  int64 telegramId = 2;
  string fullName = 3;
  string userName = 4;
  int32 age = 5;
  string gender = 6;
  string lookingFor = 7;
  string state = 8;
  int64 lastSeen = 9;
  int64 lastUpdate = 10;
  bool sleep = 11;
  string education = 12;
  string dietaryPreference = 13;
  string job = 14;
  string workout = 15;
  string sleepingHabits = 16;
  string pets = 17;
  string bio = 18;
  repeated string profileImages = 19;
  string inviteCode = 20;
  
}



